---
name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: ./test/test-results-to-csv.sh
